name: Build and Push Docker Images

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: varshitpalivela
          password: Varshit@2711

      # ---------------------------
      # Build & Push Backend Image
      # ---------------------------
      - name: Build backend image
        run: docker build -t varshitpalivela/my-backend:latest ./backend

      - name: Push backend image
        run: docker push Varshit@2711/my-backend:latest

      # ----------------------------
      # Build & Push Frontend Image
      # ----------------------------
      - name: Build frontend image
        run: docker build -t 2300033447/my-frontend:latest ./frontend

      - name: Push frontend image
        run: docker push Varshit@2711/my-frontend:latest
